Remove circular dependency #16
Try to update to Tycho 3.0.1 to resolve java.lang.NoSuchMethodError:
'void org.eclipse.equinox.internal.p2.repository.helpers.ChecksumProducer

Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>